project_name: platform
builds:
  - goos:
    - linux
    - darwin
    goarch:
    - amd64
    - arm64
    main: ./cmd/influx/
    env:
      - GO111MODULE=on
    ldflags: -s -w -X main.commit={{.Commit}}
    binary: influx
  - goos:
    - linux
    - darwin
    goarch:
    - amd64
    - arm64
    main: ./cmd/influxd/
    flags:
      - -tags=assets
    env:
      - GO111MODULE=on
    ldflags: -s -w -X main.commit={{.Commit}}
    binary: influxd
    hooks:
      pre: make generate

archive:
  format: tar.gz
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - LICENSE
  - README.md

snapshot:
  name_template: 'nightly'

s3:
  -
    bucket: dl.influxdata.com
    region: us-east-1
    folder: "platform/nightlies/"

dockers:
  - goos: linux
    goarch: amd64
    binaries:
    - influxd
    - influx
    image_templates:
      - 'quay.io/influxdb/influx:{{ .Version }}'
    dockerfile: docker/influxd/Dockerfile
    extra_files:
      - docker/influxd/entrypoint.sh

# Do not make github release
release:
  disable: true
